sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ervis23/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ervis23/docker-react npm run test
